# Generated by Django 4.2.4 on 2023-10-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='json',
        ),
    ]
