# Generated by Django 4.2.4 on 2023-09-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('mainPhoto', models.ImageField(upload_to='')),
                ('mainGif', models.ImageField(upload_to='')),
                ('mechanism', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('waterProtection', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.brandmodel')),
            ],
        ),
    ]
