# Generated by Django 4.2.4 on 2023-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
