# Generated by Django 4.2.4 on 2023-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_alter_watchmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmodel',
            name='color',
            field=models.CharField(choices=[('C1', 'color-111'), ('C2', 'color-222'), ('C3', 'color-333')], max_length=50),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='material',
            field=models.CharField(choices=[('MA1', 'Material-111'), ('2MA', 'Material-222'), ('MA3', 'Material-333')], max_length=50),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='mechanism',
            field=models.CharField(choices=[('ME1', 'Mechanism-111'), ('ME2', 'Mechanism-222'), ('ME3', 'Mechanism-333')], max_length=50),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='size',
            field=models.CharField(choices=[('S1', 'Size-111'), ('S2', 'Size-222'), ('S3', 'Size-333')], max_length=50),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='waterProtection',
            field=models.CharField(choices=[('W1', 'WaterProtection-111'), ('W2', 'WaterProtection-222'), ('W3', 'WaterProtection-333')], max_length=50),
        ),
    ]
