# Generated by Django 4.2.4 on 2023-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_alter_watchmodel_color_alter_watchmodel_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchmodel',
            name='mainGif',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='mainGif',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
